#ifndef COMP10050_ASSIGNMENT_2_CONSTANTS_H
#define COMP10050_ASSIGNMENT_2_CONSTANTS_H

// CONSTANTS FOR TWITTER
// MAX LENGTH OF A TWEET
#define TWEET_LENGTH 280
// MAX LENGTH OF USERNAMES
#define USR_LENGHT 100
// MAX NUMBER OF FOLLOWERS
#define MAX_FOLLOWERS 30
// MAX NUMBER OF FOLLOWING
#define MAX_FOLLOWING 30
// MAX NUMBER OF USERS
#define MAX_USERS 100
// NUMBER OF TWEETS TO DISPLAY
#define DISPLAY_TWEETS 10

// CONSTANTS FOR DISPLAY LIBRARY
#define COLS 4
#define ID_COL 3
#define USERNAME_COL 20
#define FOLLOWERS_COL 15
#define FOLLOWING_COL 15
#define TOTAL (ID_COL + USERNAME_COL + FOLLOWERS_COL + FOLLOWING_COL + (strlen(BORDER) * (COLS + 1)))
#define LONG_CELL (ID_COL + USERNAME_COL + FOLLOWERS_COL + FOLLOWING_COL + (strlen(BORDER) * (COLS - 1)))
#define BORDER " | "

#endif